[package]
name = "actix-basic"
version = "0.1.0"
authors = ["ibanfi@gmail.com"]
edition = "2018"

[dependencies]
actix-web="1.0.8"
actix-http="0.2.10"
reqwest="0.9.22"
serde_json = "1.0"
serde = "1.0"
validator="0.10.0"
validator_derive="0.10.0"
futures="0.1.29"
bytes="0.4.12"
json="*"
